#!/bin/sh
echo "Starting test runner..."

test_runner="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe"
tests_dll="C:\Users\Gabo-PC\Desktop\mmm\UnitHooks\HookProject\myUnitTest\bin\Debug\myUnitTest.dll"
failure_string="Failed: 0"

result=`"$test_runner" "$tests_dll" | grep "$failure_string"`
if [ -n "$result" ]
then
	echo >&2 "All tests run successfully."
	exit 0
fi
echo >&2 "Unit test are not passing! Push aborted!"
exit 1